### ISSUE TITLE
HSI可视化的问题

### ISSUE THREAD

**Issue by ljf20122010** [caiyuanhao1998/MST#12]
我使用MST++仓库中的算法得到HSI的.mat文件，之后使用MST仓库中的show_real文件进行可视化，将channel更改为1到31后并增加lam28中的数量，运行后得到报错：

Index in position 3 exceeds array bounds. Index must not exceed 1.
出错 show_real (第 25 行)
        dispCubeAshwin(recon(:,:,img_nb),intensity,lam31(img_nb), [] ,col_num,row_num,0,1,name);

如下图划线处是我更改的地方：
![EN0X3CQZTQLQV@A3RQ_QW5A](https://user-images.githubusercontent.com/33053551/196683158-074da8aa-36d5-4652-bed2-ce3c5c349226.png)

请问这样的操作流程是否正确，代码还有哪里需要更改？

**Comment by caiyuanhao1998** [comment]
从报错信息来看是越界了，应该就是尺寸不match，MST的可视化代码需要改一下才能用到MST++上边，你根据自己对代码的理解，插几个断点调一下吧。

**Comment by caiyuanhao1998** [comment]
你好，我在 MST++ 的 repo 里面加入了可视化的工具包，并调好了这个函数，你可以参考那个repo。或者我直接把它复制过来也行。你改改路径和载入的变量（cube）就可以运行了。

```shell
%% plot color pics
clear; clc;
load('simulation_results\results\ARAD_1K_0314.mat');

save_file = 'simulation_results\rgb_results\mst_s\';
mkdir(save_file);

close all;
frame = 1;

recon = cube;
intensity = 5;
for channel=1:31
    img_nb = channel;  % channel number
    row_num = 1; col_num = 1;
    lam31 = [400 410 420 430 440 450 460 470 480 490 500 510 ...
            520 530 540 550 560 570 580 590 600 610 620 630 ...
            640 650 660 670 680 690 700];
    recon(find(recon>1))=1;
    name = [save_file 'frame' num2str(frame) 'channel' num2str(channel)];
    dispCubeAshwin(recon(:,:,img_nb),intensity,lam31(img_nb), [] ,col_num,row_num,0,1,name);
end
hold on;
```

**Comment by ljf20122010** [comment]
> 你好，我在 MST++ 的 repo 里面加入了可视化的工具包，并调好了这个函数，你可以参考那个repo。或者我直接把它复制过来也行。你改改路径和载入的变量（cube）就可以运行了。
> 
> ```shell
> %% plot color pics
> clear; clc;
> load('simulation_results\results\mst_s.mat');
> save_file = 'simulation_results\rgb_results\mst_s\';
> mkdir(save_file);
> 
> close all;
> frame = 1;
> for i = 1:10
>     recon = squeeze(pred(i,:,:,:));
>     intensity = 5;
>     for channel=1:28
>         img_nb = [channel];  % channel number
>         row_num = 1; col_num = 1;
>         lam28 = [453.5 457.5 462.0 466.0 471.5 476.5 481.5 487.0 492.5 498.0 504.0 510.0...
>             516.0 522.5 529.5 536.5 544.0 551.5 558.5 567.5 575.5 584.5 594.5 604.0...
>             614.5 625.0 636.5 648.0];
>         recon(find(recon>1))=1;
>         name = [save_file 'frame' num2str(frame) 'channel' num2str(channel)];
>         dispCubeAshwin(recon(:,:,img_nb),intensity,lam28(img_nb), [] ,col_num,row_num,0,1,name);
>     end
>     frame = frame+1;
> end
> close all;
> ```

您好，不好意思才看到回复，已经用您的工具包实现了可视化，谢谢。

**Comment by Vzhouhan** [comment]
请问可视化的代码中intensity设置为多少呢

**Comment by caiyuanhao1998** [comment]
> 请问可视化的代码中intensity设置为多少呢

这个你可以自行调整，只要所有的方法弄得一样就行

**Comment by Vzhouhan** [comment]
您论文里的结果设置的是多少呢？

**Comment by caiyuanhao1998** [comment]
可能是2，可能是4，你试一下吧

**Comment by Vzhouhan** [comment]
> 可能是2，可能是4，你试一下吧

好的，非常感谢
