### ISSUE TITLE
real data training

### ISSUE THREAD

**Issue by Vzhouhan** [caiyuanhao1998/MST#14]
在真实集训练时，cave尺寸是512方的，我们在复现时似乎遇到了麻烦。具体来讲，真实实验模型要求传递660*660尺寸的图像，而cave的尺寸达不到该要求。如果我理解的没有错，这里是否使用了1024版本的cave？我将不胜感激如果可以收到您的答复。

**Comment by caiyuanhao1998** [comment]
对的，simulation的时候要用CAVE 512×512，切出256×256的patch训练。real 训练的时候要用 CAVE 1024×1024，切出660×660的patch训练。在data prepare那里都有提供这两个数据集的下载链接。

**Comment by Vzhouhan** [comment]
谢谢你的评论解决了我的困惑。尽管如此，我在随后的复现工作中又遇到了新的困难。我已经仔细查看了作者在真实实验中的可用代码，其中图像尺寸被裁切为了384，并且cave数据集中只取了30张图。我想知道代码中的默认设置是否不适合于660*660的图像，或许我应该尝试将cave的图像选择由默认的30张更改为1024版本的205张？此外，如果是针对384*384的图像所设计的代码，应该如何将观测图像采样至适合维度？

**Comment by caiyuanhao1998** [comment]
我们训练的时候将图像裁成384是为了节省计算量。你可以完全采用我们的默认设定。训练张数就用30张即可。
当然你可以试一下把训练张数扩大到205张，只是那样比较费时间。

**Comment by Vzhouhan** [comment]
对您的耐心表示感谢。我们试图采用您所推荐的第一种方法，即，将图像裁切至384，对模型进行训练。然而，这将导致一个问题，我需要在测试时对真实获取的观测图像进行裁切。换句话讲，我需要将660x714尺寸的观测图像裁切至384x438。我的疑惑在于，在使用真实观测图像进行测试时，裁切操作只是torch中的数组行列选取还是对整张图像进行指定步长采样操作？或者在测试时有其他方法可以通过尺寸为384训练的模型对660的观测进行直接重建？

**Comment by caiyuanhao1998** [comment]
测试的时候不用裁剪，直接用660×660测。你可以看看我们的real测试代码

**Comment by Vzhouhan** [comment]
非常感谢，祝您生活愉快！

**Comment by dongruoyu1** [comment]
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/c02d17b0-4dd3-4532-9f35-89a317f40d43)
readme里面说的是模拟数据集用的1024方，真是数据集用的512方和KAIST的，所以是readme写错了吗
