### ISSUE TITLE
TSA_simu_data/mask_3d_shift.mat 数据如何获得。

### ISSUE THREAD

**Issue by Junyu99** [caiyuanhao1998/MST#15]
您好，我们最近在关注您的DAUHST的工作。在阅读您的代码中，发现您的代码加载的mask的数据为 ‘TSA_simu_data/mask_3d_shift.mat’（shape ->256x310x28）。
请问这个mask 形式是如何获得的？它和‘TSA_simu_data/mask.mat ’中的数据有什么关系？

**Comment by caiyuanhao1998** [comment]
你好，你说的这个mask是TSA作者提供的，他们的这个mask是二维的mask (单通道)，经过复制后得到的28通道的3d的mask。你可以看看TSANet原文关于CASSI的公式推导。

![屏幕快照 2022-11-24 下午10 40 30](https://user-images.githubusercontent.com/48472661/203810566-5b7c010c-26e2-4a3a-a8ff-4217586523ce.png)

[1] [End-to-end low cost compressive spectral imaging with spatial-spectral self-attention](https://link.springer.com/chapter/10.1007/978-3-030-58592-1_12)

**Comment by Junyu99** [comment]
好的，我可能记错了。以为是您DAUHST提供的。
但是我发现这个数据不是简单把mask 进行平移，得到28通道的3d mask。
我疑惑的地方是平移后padding的部分数据不知道如何获取的。（比如第0通道的[:, 256:,0], 第1通道的[:,:2,1] , [:,258:,1],...）
我去检查一下TSANet工作的paper。谢谢您的回复。

**Comment by caiyuanhao1998** [comment]
嗯嗯，如果你觉得我们的代码有帮助的话，帮忙点点star，fork

**Comment by Junyu99** [comment]
好的，再次感谢~

**Comment by caiyuanhao1998** [comment]
好嘞，也感谢你~

**Comment by zouge357** [comment]
> 好的，我可能记错了。以为是您DAUHST提供的。 但是我发现这个数据不是简单把mask 进行平移，得到28通道的3d mask。 我疑惑的地方是平移后padding的部分数据不知道如何获取的。（比如第0通道的[:, 256:,0], 第1通道的[:,:2,1] , [:,258:,1],...） 我去检查一下TSANet工作的paper。谢谢您的回复。

您好，请问您现在清楚了吗，我也在疑惑怎么得到的
