### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by PerfectBIN** [caiyuanhao1998/MST#16]
您好，感谢您的出色工作，您文章里引用的9个算法当中，TwIST，GAP-TV，HSSP，DNU，DIP-HSI的实验结果或者源码没有在您的主页找到，请问您可以发一下吗，期待您的回复。

**Comment by caiyuanhao1998** [comment]
同学你好，我们这个repo主要是针对光谱压缩成像的深度学习算法，TwIST，GAP-TV，DIP-HSI都不是learning based的方法。HSSP作者没有开源代码，DNU的话可以参考以下链接：

 https://github.com/wang-lizhi/DeepNonlocalUnrolling

**Comment by PerfectBIN** [comment]
您能提供一下这些算法在您文章里的结果图吗，我想跟我复现的比对一下，期待您的回复。

**Comment by caiyuanhao1998** [comment]
文章中的结果图是用他们原文提供的代码运行得到或者就是直接邮件与作者联系后获得的结果图。
建议你去用他们的官方代码或者给原文作者发邮件咨询一下。

**Comment by PerfectBIN** [comment]
谢谢~
