### ISSUE TITLE
self.HSI

### ISSUE THREAD

**Issue by Sebastian970107** [caiyuanhao1998/MST#17]
在dataset中有写到如果是test模式的话为 hsi = self.HSI[:, :, :, index1] 请问这里的HSI是什么数据集呢，代码中似乎没有交代。

**Comment by caiyuanhao1998** [comment]
你说的这个代码的位置在哪？

**Comment by Sebastian970107** [comment]
real/train_code/dataset.py    除了cave和kaist之外似乎应该还有一个数据集

**Comment by caiyuanhao1998** [comment]
对的，real进行test的时候，用到了一个真实的数据集，是由TSA-Net这篇文章搜集的。我们也有在data_preparation里面提供下载链接
