### ISSUE TITLE
关于测试指标问题

### ISSUE THREAD

**Issue by Sebastian970107** [caiyuanhao1998/MST#18]
文章中在关于仿真数据的测试细节中写道，从KAIST数据集中选取10个样本，裁剪成256*256大小的数据输入到网络中得到ssim和psnr的相关指标。这里想问一下，KAIST数据的空间分辨率在2000+*3000+，文章中的指标是随机裁剪后得到的最优指标吗，因为随机裁剪的话他的指标差异会很大。

**Comment by caiyuanhao1998** [comment]
训出来没有差异很大

**Comment by Sebastian970107** [comment]
ＫＡＩＳＴ数据集中每张图片大部分像素点是背景，文章中的指标是某一次随即裁剪的最优值吗

**Comment by caiyuanhao1998** [comment]
不是，你可以试试看跑一遍代码

**Comment by Sebastian970107** [comment]
嗯嗯看明白了，论文中”Following the schedule of TSA-Net [36], we adopt CAVE as the training set. 10 scenes from KAIST are selected for testing.” 这句话似乎有歧义，测试集应该是TSA_simu_data.
