### ISSUE TITLE
could you provide the training logs about DAUHST model?

### ISSUE THREAD

**Issue by Junyu99** [caiyuanhao1998/MST#19]
I am very interesed in your DAUHST work and reproducing your expermental work. 
Could you prvoid the training logs of DAUHST, it would be helpful to have training logs to inspect the correctness of the training process.

**Comment by caiyuanhao1998** [comment]
What problem have you encountered?

**Comment by Junyu99** [comment]
We have trained DAUHST-2stg, 3stg, 5stg model by using your provided source code and commands. And we got the results as follows:

**Comment by Junyu99** [comment]
We have trained DAUHST-2stg, 3stg, 5stg model by using your provided source code and commands. And we got the results as follows:
2stg: Epoch 296: testing psnr = 36.35, ssim = 0.957, time: 0.05 (PSNR,SSIM: 36.34/0.952 in paper, +0.01/+0.005)
3stg: Epoch 277: testing psnr = 36.95, ssim = 0.963, time: 0.06 (PSNR,SSIM: 37.21/0.959 in paper, -0.26/+0.004)
5stg: Epoch 242: testing psnr = 37.62, ssim = 0.968, time: 0.22 (PSNR,SSIM: 37.75/0.962 in paper, -0.13/+0.006)

It is confusing to me that PSNR results of DAUHSR-3stg and 5stg model we have trained are worse than the results in your paper, but the SSIM results of DAUHST-3stg and 5stg model are better than the results in your paper.  

Does the random seed affect the results so much?

**Comment by caiyuanhao1998** [comment]
This is the relative training error within a reasonable range.
It is OK. I suggest you to train several times if you are not satisfied.

**Comment by Junyu99** [comment]
Alright, thanks for your reply.

**Comment by caiyuanhao1998** [comment]
You are welcome
