### ISSUE TITLE
Baidu Disk links do not open

### ISSUE THREAD

**Issue by nikhilCad** [caiyuanhao1998/MST#2]
Hello, the Baidu Disk links are not opening in my country. Can you consider putting those files on OneDrive or Google Drive?

**Comment by caiyuanhao1998** [comment]
which files do you mean?

**Comment by nikhilCad** [comment]
The 2 Baidu Disk files in "Prepare dataset"

CAVE_512_28 and KAIST_CVPR2021

**Comment by caiyuanhao1998** [comment]
All right, I will fix it and inform you when it is done.

**Comment by caiyuanhao1998** [comment]
The data has been uploaded to onedrive. 
please refer to README.md
