### ISSUE TITLE
归一化问题

### ISSUE THREAD

**Issue by Sebastian970107** [caiyuanhao1998/MST#21]
请问在对原始数据的处理中需要归一化到［0，1］之间吗，在代码中似乎没有做类似的操作。此外 input = meas / 28 * 2 * 1.2 是什么意思呢

**Comment by Sebastian970107** [comment]
# QE, bit = 0.4, 2048
# input = np.random.binomial((input * bit / QE).astype(int), QE)
# input = np.float32(input) / np.float32(bit)
以及这里所做的处理是不是类似于归一化的操作呢

**Comment by caiyuanhao1998** [comment]
不需要归一化操作，光谱数据本身经过特殊采集和处理。

**Comment by caiyuanhao1998** [comment]
我注意到你提了很多的issue，感谢你对我们工作的关注，要是你觉得我们的代码有用的话，麻烦star，fork支持一下

**Comment by Sebastian970107** [comment]
sure!
