### ISSUE TITLE
一点点疑问

### ISSUE THREAD

**Issue by meixiaoyinn** [caiyuanhao1998/MST#22]
你好，数据集里TSA_real_data的Measurements是加噪之后得到的吗

**Comment by caiyuanhao1998** [comment]
Measurements是通过CASSI系统，真实采集得到，本身自带噪声

**Comment by meixiaoyinn** [comment]
好的，谢谢

**Comment by caiyuanhao1998** [comment]
嗯嗯，不客气，如果感觉我们代码有用的话，帮忙点点star，fork支持一下
