### ISSUE TITLE
real and simulation dataset

### ISSUE THREAD

**Issue by Sebastian970107** [caiyuanhao1998/MST#26]
您好，想问一下，在您提供的simulation代码中显示 opt.data_path = f"{opt.data_root}/cave_1024_28/"，似乎您在simulation下训练时用的是cave 1024尺寸的数据集，而在real下用的是cave 512尺寸的数据集，这与您在之前issue中说明的有些出入，请问这里这两个数据集的选取对指标影响大吗，您在这两种情况下是怎样选取的数据集呢？谢谢！

**Comment by caiyuanhao1998** [comment]
没对这些数据的尺寸做过特殊的处理，就直接按照TSA-Net的设置训练。你可以尝试改变一下尺寸，在simu上直接可以看指标，real上需要定期测试存图，看视觉效果进行挑选。
