### ISSUE TITLE
可视化生成的图片与作者百度网盘中提供的图片大小不一致

### ISSUE THREAD

**Issue by chenjiachengzzz** [caiyuanhao1998/MST#27]
您好，首先感谢您做出这么棒的工作，并且无私的开源出来。在运行可视化matlab代码时,我生成的图片与作者生成的图片不一致。
![frame1channel1](https://user-images.githubusercontent.com/54382260/234293866-60ff749c-ae14-4ce7-b30c-1aa705800970.png)
![frame1channel1](https://user-images.githubusercontent.com/54382260/234293910-a4407e33-232b-4fa5-8663-4b795c1d3fd7.png)
第一张是我生成的，第二张是作者提供的，我想知道为何出现这种问题，是作者已经裁剪过图像了嘛？希望得到您的解答！

**Comment by caiyuanhao1998** [comment]
你好，感谢你的关注。用matlab可视化代码直接生成的图片是带白边的，提供在百度网盘里的图片是裁剪过后的。
你可以使用裁剪软件或者写一个裁剪代码来实现这一功能，以下是我自己写的一个裁剪代码，供你参考：

```shell
%Cut Out
clear all
method = ["MST","CST","DAUHST","MST_pp","HDNet","Truth"];
frame = 'frame1';
channel = ["channel6","channel16","channel21","channel28"];
save_dir = strcat(frame,'_simulation_compare_no_box\');
mkdir(save_dir);

for i=1:length(method)
    for j=1:length(channel)
        I = imread(strcat('simulation_results\rgb_results\',method(i),'\',frame,channel(j),'.png'));
        rect = [181 37 553 553];
        I_crop = imcrop(I,rect);
        imwrite(I_crop,strcat(save_dir,method(i),'_',channel(j),'.png'));
    end

end
```

**Comment by chenjiachengzzz** [comment]
> 你好，感谢你的关注。用matlab可视化代码直接生成的图片是带白边的，提供在百度网盘里的图片是裁剪过后的。 你可以使用裁剪软件或者写一个裁剪代码来实现这一功能，以下是我自己写的一个裁剪代码，供你参考：
> 
> ```shell
> %Cut Out
> clear all
> method = ["MST","CST","DAUHST","MST_pp","HDNet","Truth"];
> frame = 'frame1';
> channel = ["channel6","channel16","channel21","channel28"];
> save_dir = strcat(frame,'_simulation_compare_no_box\');
> mkdir(save_dir);
> 
> for i=1:length(method)
>     for j=1:length(channel)
>         I = imread(strcat('simulation_results\rgb_results\',method(i),'\',frame,channel(j),'.png'));
>         rect = [181 37 553 553];
>         I_crop = imcrop(I,rect);
>         imwrite(I_crop,strcat(save_dir,method(i),'_',channel(j),'.png'));
>     end
> 
> end
> ```
哇 yuanhao大哥 也太强了，太感谢您了啊。
