### ISSUE TITLE
关于DAUHST

### ISSUE THREAD

**Issue by Vzhouhan** [caiyuanhao1998/MST#29]
作者您好，在您的公布的DAUHST源码中，我注意到在迭代阶段的shift_back_3d和 shift_3d这两个函数的输入和输出没有区别，如果我没有做错的话，可以向您请教下这两个函数的作用吗？

**Comment by caiyuanhao1998** [comment]
shift_3d是模拟CASSI色散的偏移，shift_back_3d是shift_3d的逆变换。
