### ISSUE TITLE
There is no product of V and Mask Attention in MS-MSA

### ISSUE THREAD

**Issue by Smile-QT** [caiyuanhao1998/MST#3]
There is no product of V and Mask Attention in MS-MSA

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your attention

We found that using MM in real experiments will increase the training time but bring minimal improvements. Thus, we do not perform conduct between V and Mask. Feel free to try this using our code.

**Comment by luluchou** [comment]
作者是个傻逼！专门盗我号给他自己刷星星！干！
