### ISSUE TITLE
请问MST这篇论文中的 图6是怎么画的？

### ISSUE THREAD

**Issue by WFMOOK** [caiyuanhao1998/MST#30]
尊敬的作者您好，您在HSI重建领域做出了一系列非常棒的工作，并且开源了一个非常棒的工具箱，对你表示尊敬。我对您发表在cvpr2022上的MST非常感兴趣，您在论文的图6中展示了一种可视化图来说明所提出的S-MSA机制的有效性，我想知道这种可视化应该如何操作。希望得到您的回复，再次感谢！

**Comment by caiyuanhao1998** [comment]
对高光谱图像（HxWxC）的通道两两计算相关系数，然后会得到一个C×C的矩阵，然后将这个矩阵用伪彩色可视化出来便得到图6中的样子。

**Comment by WFMOOK** [comment]
> 对高光谱图像（HxWxC）的通道两两计算相关系数，然后会得到一个C×C的矩阵，然后将这个矩阵用伪彩色可视化出来便得到图6中的样子。

非常感谢您的及时回复！是采用和计算CxC维度的attention类似的方式吗。就是CxHW @ HWxC 然后得到一个CxC的矩阵吗？

**Comment by caiyuanhao1998** [comment]
不是，是计算两个矩阵的相关系数。一个通道是一个矩阵。

**Comment by WFMOOK** [comment]
> 不是，是计算两个矩阵的相关系数。一个通道是一个矩阵。

好的 再次感谢您的耐心回复！ 请问相关系数是采用什么方式计算的。

**Comment by caiyuanhao1998** [comment]
这个可以搜一下python或pytorch有关的库。百度谷歌一搜就有。

**Comment by WFMOOK** [comment]
> 这个可以搜一下python或pytorch有关的库。百度谷歌一搜就有。

好的 谢谢您！

**Comment by zhangzheng2242** [comment]
我也尝试做了一下光谱相关性矩阵的可视化。发现MST论文fig6的相关性矩阵是场景5的，但是论文中展示的RGB是场景4的，会不会是索引从0开始而没有加1
