### ISSUE TITLE
关于数据集的询问

### ISSUE THREAD

**Issue by tianguangjianhan** [caiyuanhao1998/MST#31]
请问一下代码架构中datasets的cave_1024_28文件夹下的数据是怎么获取的呀，是通过自己设计的mask对CAVE进行实验得到的吗

**Comment by caiyuanhao1998** [comment]
这个是CAVE数据集空间尺寸为1024×1024，通道为28的训练数据，由TSA-Net的官方代码提供：
https://github.com/mengziyi64/TSA-Net

**Comment by tianguangjianhan** [comment]
大佬可否加个联系方式想请教一些重建的问题感谢感谢
