### ISSUE TITLE
truth.mat in show_line.m?

### ISSUE THREAD

**Issue by bryanbocao** [caiyuanhao1998/MST#35]
In ```MST/visualization/```

Line 3 requires ```truth.mat``` in the ```show_line.m```:

```
load(['simulation_results\results\','truth','.mat']);
```
https://github.com/caiyuanhao1998/MST/blob/5b40916526dc9da3f7515f5cd5978251cc6035a9/visualization/show_line.m#L3C1-L3C54

It would be great to help specify which ```truth.mat``` we should put here. Thanks!

**Comment by caiyuanhao1998** [comment]
`truth.mat` is the ground truth containing all ten simulation scenes. The parameter `f=2` controls which scene to be visualized.

**Comment by bryanbocao** [comment]
Thanks for the reply!
(1) By ```ten simulation scenes``` I assume you refer to ONLY ```TSA_simu_data``` dataset:
```
        |--TSA_simu_data  
            |--mask.mat   
            |--Truth
                |--scene01.mat
                |--scene02.mat
                ： 
                |--scene10.mat
```
?

(2) When I do not have results from other models, do I have to comment out the code for other models manually like:
![Screenshot from 2023-08-20 22-09-25](https://github.com/caiyuanhao1998/MST/assets/14010288/6d654c49-9113-4bca-b083-00dbd3d38074)
?

**Comment by caiyuanhao1998** [comment]
(1) Yes

(2) Yes, you can try code or modify it
