### ISSUE TITLE
Real Test Data and Masks?

### ISSUE THREAD

**Issue by bryanbocao** [caiyuanhao1998/MST#36]
README.md mentions that
```
Both the CAVE (CAVE_512_28) and KAIST (KAIST_CVPR2021) datasets are used as the real training set.
```
But there are no clues which datasets should we put into these two paths
https://github.com/caiyuanhao1998/MST/blob/main/real/test_code/test.py
https://github.com/caiyuanhao1998/MST/blob/5b40916526dc9da3f7515f5cd5978251cc6035a9/real/test_code/test.py#L13-L14
```
parser.add_argument('--data_path', default='./Data/Testing_data/', type=str,help='path of data')
parser.add_argument('--mask_path', default='./Data/mask.mat', type=str,help='path of mask')
```

Thanks!

**Comment by caiyuanhao1998** [comment]
Test data is the five real scenes. Please refer to data preparation. Mask file can also be found there.

**Comment by bryanbocao** [comment]
Thanks for your response. This might be obvious to you since you developed the code. These is still some ambiguity from my point of view. The repo shows different datasets including CAVE, KAIST and TSA.

By "five real scenes", did you specifically refer to ONLY the following dataset:
```
        |--TSA_real_data  
            |--mask.mat   
            |--Measurements
                |--scene1.mat
                |--scene2.mat
                ： 
                |--scene5.mat
```
?

Thanks!

**Comment by caiyuanhao1998** [comment]
Yes, you got them

**Comment by bryanbocao** [comment]
Great. Thanks for your clarification!

Some follow-up questions are 

The real train code trains a model on CAVE and KAIST:
https://github.com/caiyuanhao1998/MST/blob/592376dbd932bb00d73440d9cfffec794c2bb7eb/real/train_code/train.py#L21-L22

but the real test code tests the model on a different dataset ```TSA_real_data```. 

(1) Is that what it is supposed to be? Is it the common practice for real data benchmark?
(2) Is that how the scores (PSNR, SSIM) are computed in the paper?

Thanks!

**Comment by caiyuanhao1998** [comment]
(1) Yes

(2) Real dataset has no gt. We do not comput PSNR / SSIM on this dataset

**Comment by bryanbocao** [comment]
Thanks for your reply.

When I specify
```
parser.add_argument('--data_path', default='../../datasets/TSA_simu_data/Truth/', type=str,help='path of data')
parser.add_argument('--mask_path', default='../../datasets/TSA_real_data/mask.mat', type=str,
                    help='path of mask')
```

```
Traceback (most recent call last):
  File "test.py", line 60, in <module>
    HR_HSI = prepare_data(opt.data_path, 5)
  File "test.py", line 40, in prepare_data
    HR_HSI[:,:,idx] = data['meas_real']
KeyError: 'meas_real'
```
```
 27 def prepare_data(path, file_num):
 28     HR_HSI = np.zeros((((660,714,file_num))))
 29     for idx in range(file_num):
 30         ####  read HrHSI
 31         idx = str(idx + 1)
 32         while len(idx) < 2: idx = '0' + idx
 33         path1 = os.path.join(path) + 'scene' + idx + '.mat'
 34         data = sio.loadmat(path1)
 35         # debug
 36         print('\n\n\n==========')
 37         print('data: ', data)
 38         print('data.keys(): ', data.keys())
 39         # debug
 40         HR_HSI[:,:,idx] = data['meas_real']
 41         HR_HSI[HR_HSI < 0] = 0.0
 42         HR_HSI[HR_HSI > 1] = 1.0
 43     return HR_HSI
```
Any help would be great.

**Comment by caiyuanhao1998** [comment]
You may download the wrong measurement. Just read and print the keys of the downloaded data to have a check.

**Comment by bryanbocao** [comment]
> You may download the wrong measurement. Just read and print the keys of the downloaded data to have a check.

(1) Thanks for your reply. That's exactly what I was trying to do in the previous code:
```
 36         print('\n\n\n==========')
 37         print('data: ', data)
 38         print('data.keys(): ', data.keys())
```
(2) I just followed the instructions exactly in the ```README.md``` and downloaded TSA_real_data ([One Drive](https://1drv.ms/u/s!Au_cHqZBKiu2gYFTpCwLdTi_eSw6ww?e=uiEToT)) with the structure:
```
|--MST
    |--datasets
        |--TSA_real_data
            |--mask.mat   
                |--Measurements
                    |--scene1.mat
                    |--scene2.mat
                     ： 
                    |--scene5.mat
  
```
but still got the same error.

If this link TSA_real_data ([One Drive](https://1drv.ms/u/s!Au_cHqZBKiu2gYFTpCwLdTi_eSw6ww?e=uiEToT))  provides the wrong measurement, could you tell me which link to download?
Thanks!

**Comment by caiyuanhao1998** [comment]
Unfortunately, we do not have an additional link. Sorry.

I will have a check again after CVPR 2024.

**Comment by bryanbocao** [comment]
@caiyuanhao1998 Thanks for your response. I am also debugging during weekends. Looks like just some data formatting.
