### ISSUE TITLE
mask_3d_shift和phi的关系

### ISSUE THREAD

**Issue by liuli33** [caiyuanhao1998/MST#37]
您好我想请教一下，在阅读论文的时候看到，在多数建模的过程中都是通过向量化建模，phi是表示系统矩阵，实际上是包含了色散后相加的过程。但是在dauhst代码实现的过程中变成了图片级别的实现，而phi变成了mask_3d_shift，通道相加则是通过额外的代码实现的。
这样的求解是等效于向量化的求解吗？为什么？

**Comment by caiyuanhao1998** [comment]
是等效的，因为仅仅只有维度上的区别。处理成图片（tensor）级别是为了适应 pytorch 使用 CNN 和 Transformer来加速处理，高效计算。请别担心。
