### ISSUE TITLE
你好，想请教一个问题

### ISSUE THREAD

**Issue by lxh2lm** [caiyuanhao1998/MST#38]
基于RGB的光谱重建的数据集制作，能否通过某个特定的RGB相机配合不同的窄带滤波片获得同一物体的各波段图片，进而组合成一个光谱图用于训练。这样在特定相机下的训练结果能否提升获取的RGB图片重建效果？换言之就是重建的网络过程中，除了RGB图片信息本身以外，可以学到相机响应函数吗？

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，请问你是指学一个 从 RGB 到高光谱 HSI 图像的映射吗？如果是的话，这个是可以做到的。我们的扩展工作 [MST++](https://arxiv.org/pdf/2204.07908.pdf) 便实现了这个功能，在去年的 NTIRE Spectral Recovery from RGB Challenge 中获得了冠军，请参考我们这个 [repo](https://github.com/caiyuanhao1998/MST-plus-plus) 来了解更多内容
