### ISSUE TITLE
real任务中所提供的gap-net与其他的不一样

### ISSUE THREAD

**Issue by zhangzheng2242** [caiyuanhao1998/MST#39]
real任务中所提供的gap-net的rgb结果与其他的不一样
gap-net很明显的是四周有黑色边框，其他的图片会铺满整个图片
我用提供的mat重新生成的rgb也是如此
想请问下这个是gap-net的问题吗

**Comment by zhangzheng2242** [comment]
![image](https://github.com/caiyuanhao1998/MST/assets/103888494/219a34da-29ff-423b-9b01-db7d7c533256)
好像是少了100分辨率
应该是660x660

**Comment by caiyuanhao1998** [comment]
对的，具体的细节可以参考gap-net官方的repo：

https://github.com/mengziyi64/GAP-net
