### ISSUE TITLE
测试代码问题

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#40]
真实数据集的测试代码是不是有误，没法正确运行，显示test.py: error: unrecognized arguments: --template mst_l --outf ./exp/mst_l/ --method mst_l

**Comment by caiyuanhao1998** [comment]
报错信息是什么？发出来看一下

**Comment by dongruoyu1** [comment]
test.py: error: unrecognized arguments: --template mst_l --outf ./exp/mst_l/ --method mst_l
test文件里面确实没有这几个参数，是疏忽了吗

**Comment by dongruoyu1** [comment]
还有一个问题，为什么要分为模拟和真实实验呀，模拟是指将HSI在matlab上经过mask和色散后得到measurement，然后将measurement放入网络中测试，真实实验是指直接通过CASSI系统得到的measurement放入网络进行测试，是这样理解吗？研一刚接触这个方向不太明白，如果能解答的话真的万分感谢！

**Comment by caiyuanhao1998** [comment]
对的，你理解得对。
real test脚本我之前跑是没有问题，我等到CVPR之后再检查一下。
如果感觉有帮助的话，帮忙点点star支持一下

**Comment by dongruoyu1** [comment]
好的，真的非常感谢您的回复！对于real test脚本，具体来说是如下的错误
![error](https://github.com/caiyuanhao1998/MST/assets/128362316/64a622a7-5a45-428d-961a-ac5868e2dded)
正如下方红字所示，在运行readme文件所说的python test.py --template mst_l --outf ./exp/mst_l/ --method mst_l --pretrained_model_path ./model_zoo/mst/mst_l.pth，下方错误显示没有模板template和outf以及方法method的参数，而您在代码中确实没有parser.add_argument这些参数。您知道是怎么回事吗？
还有一个小问题，如果模拟数据HSI经过编码孔径使用的mask脚本，那么模拟色散的脚本在哪里呢？非常期待您的回复！谢谢！

**Comment by caiyuanhao1998** [comment]
你好，我在`test.py`里面加了一行：

```shell
from option import opt
```
现在外部参数问题应该解决了，你再尝试运行一下，还有别的问题就贴在这里。

模拟色散就是平移然后叠加。在加载数据的代码中。

**Comment by dongruoyu1** [comment]
import opt后还是不可以运行，报错信息和之前一样。另外我发现real中test的option.py与train的option.py两个代码是一模一样的，是否是疏忽导致的？因为感觉测试和训练所用的参数选项应该是不一样的。

**Comment by dongruoyu1** [comment]
你好博主，能看见消息吗  ┭┮﹏┭┮

**Comment by caiyuanhao1998** [comment]
按说应该是没问题的，参数已经在option里面导入了，你再试着debug一下？

**Comment by dongruoyu1** [comment]
real中test的option.py与train的option.py两个代码是一模一样的，是本来就这样写的吗
