### ISSUE TITLE
Limited by RAM?

### ISSUE THREAD

**Issue by bryanbocao** [caiyuanhao1998/MST#41]
https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40

The # scenes is greater than ```205``` in the ```cave``` dowloaded folder. Is this number ```205``` determined empirically by a machine's RAM limit?

**Comment by caiyuanhao1998** [comment]
No, it is because we do not use so many images. Using fewer images can save training time.

**Comment by dongruoyu1** [comment]
> https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40
> 
> The # scenes is greater than `205` in the `cave` dowloaded folder. Is this number `205` determined empirically by a machine's RAM limit?

Hello, may I ask if you can run the test.py script in the real experiment?

**Comment by bryanbocao** [comment]
> No, it is because we do not use so many images. Using fewer images can save training time.

@caiyuanhao1998 
Using few images can save both training time and memory but will also reduce the diversity of the training samples, Right?

**Comment by bryanbocao** [comment]
> > https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40
> > 
> > The # scenes is greater than `205` in the `cave` dowloaded folder. Is this number `205` determined empirically by a machine's RAM limit?
> 
> Hello, may I ask if you can run the test.py script in the real experiment?

No, I ran the train.py code on simulation as the reference [MST/simulation/train_code/utils.py](https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40) indicates. It has nothing to do with real experiments. Why asking? @dongruoyu1

**Comment by dongruoyu1** [comment]
> > > https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40
> > > 
> > > The # scenes is greater than `205` in the `cave` dowloaded folder. Is this number `205` determined empirically by a machine's RAM limit?
> > 
> > 
> > Hello, may I ask if you can run the test.py script in the real experiment?
> 
> No, I ran the train.py code on simulation as the reference [MST/simulation/train_code/utils.py](https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40) indicates. It has nothing to do with real experiments. Why asking? @dongruoyu1

In section 5.2 of the readme file, the author provided the code for '“python test.py --template mst_s --outf ./exp/mst_s/ --method mst_s --pretrained_model_path ./model_zoo/mst/mst_s.pth”', but did not provide a pre trained model. Do you think this code is incorrect?

**Comment by bryanbocao** [comment]
> > > > https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40
> > > > 
> > > > The # scenes is greater than `205` in the `cave` dowloaded folder. Is this number `205` determined empirically by a machine's RAM limit?
> > > 
> > > 
> > > Hello, may I ask if you can run the test.py script in the real experiment?
> > 
> > 
> > No, I ran the train.py code on simulation as the reference [MST/simulation/train_code/utils.py](https://github.com/caiyuanhao1998/MST/blob/4e91b95e74d340f915017f8439621954ca2ed1c1/simulation/train_code/utils.py#L40) indicates. It has nothing to do with real experiments. Why asking? @dongruoyu1
> 
> In section 5.2 of the readme file, the author provided the code for '“python test.py --template mst_s --outf ./exp/mst_s/ --method mst_s --pretrained_model_path ./model_zoo/mst/mst_s.pth”', but did not provide a pre trained model. Do you think this code is incorrect?

@dongruoyu1 I think 5.2 real test code is incorrect (maybe the author is too busy :)) By pre-trained model I assume you only meant real data and I couldn't find it as well.

This is what I got when I ran it directly:
https://github.com/caiyuanhao1998/MST/issues/36
