### ISSUE TITLE
为什么测试结果是包含了truth

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#42]
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/abeac85e-8d65-4f93-a093-4ce8eb75b2b1)
如图所示，pred是4-D的我理解，代表了我们得到的训练结果一共10张图片，每一张都包含28张高光谱图片，那么truth的意义是什么呢？

**Comment by caiyuanhao1998** [comment]
是真值，计算PSNR和SSIM用的

**Comment by dongruoyu1** [comment]
谢谢您，那么也就是说用不同模型测试得到的pred是不一样的，但是truth都是同一批高光谱图片？

**Comment by bryanbocao** [comment]
> 但是truth都是同一批高光谱图片？

@dongruoyu1 
Simulation里面是的，论文写Benchmark用KAIST 10 scenes，测试不同模型pred与Grount truth的visual差距，以PSNR和SSIM的metrics来测量。PSNR和SSIM都是reference-based的metrics，以ground truth为reference.
