### ISSUE TITLE
readme文件中的一些小疑问

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#43]
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/5bfccd6d-7cf7-47f3-90f9-b76a16eacf12)
您好！很抱歉再次打扰您！如图所示，在5.2test中实际上是没有给出预训练模型的，模型要通过我们自己训练得到而非model_zoo，因此此处是否应该修改？诸如python test.py --template mst_s --outf ./exp/mst_s/ --method mst_s --pretrained_model_path ./model_zoo/mst/mst_s.pth，更像是simulation的测试代码。

**Comment by caiyuanhao1998** [comment]
real model没有给出，需要你自己训一下，用我们的训练代码跑一下就好

**Comment by dongruoyu1** [comment]
谢谢您的解答，真的非常感谢！
此外，我下载完cave1024数据集后，发现里面一共242个文件，与您在README中205不一致，是否需要将多余的给删除掉？
![833cb539b4d5b3215c217c41cfa1f13](https://github.com/caiyuanhao1998/MST/assets/128362316/88fe25e4-0826-4088-8292-aaa18279a924)
