### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#44]
![78D3558BFDCB49758E3B1E4F4F7564E1](https://github.com/caiyuanhao1998/MST/assets/128362316/3370e613-1edf-4fbd-859e-5b232f15fa2f)

博主你好，我在real数据集训练模型的时候，发现加载两遍数据集，如图所示，loading CAVE 0直到loading CAVE 29，然后开始loading KAIST，KAIST的数据集加载完之后，重新加载CAVE，您知道这是怎么一回事吗？
另外，当两遍数据集全部加载后，出现了这样的错误：ran out of input。
![a9410a3db9ec4e27176f35cbf1b5321](https://github.com/caiyuanhao1998/MST/assets/128362316/a64ff5b5-5792-4d3b-bac7-bec18d275664)

**Comment by bryanbocao** [comment]
一种可能是KAIST data没load到，maybe check the path to the KAST dataset.

**Comment by caiyuanhao1998** [comment]
因为你用的是windows系统，换成ubuntu来运行就好

**Comment by bryanbocao** [comment]
@dongruoyu1 如果你还是想在windows下train的话修改好路径，比如"/" -> "\\"。一般建议在ubuntu上做training和testing。
