### ISSUE TITLE
测试代码问题

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#45]
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/522b9ec9-c408-4b01-97a1-34f076fe7626)
学长你好，我在上个问题中，将num_worker从8修改为0之后可以成功训练模型，将训练好的模型进行测试，出现了以下的bug，在csdn上也找不到解决办法，所以想来请教一下您，说是参数有问题，但是您的代码我也没怎么修改过呀。

**Comment by caiyuanhao1998** [comment]
用 ubuntu 跑

**Comment by dongruoyu1** [comment]
> 用 ubuntu 跑

谢谢您的回复，我试试看。
还有一个小问题，在阅读代码的时候，看到了mask_3d_shift_s，mask是初始二维掩码660×660，mask_3d是mask经过28次复制后得到的660×660×28，而mask_3d_shift是经过平移后得到的660×714×28，那么mask_3d_shift_s是将mask_3d_shift每一个像素平方后，在图片维度相加，得到的尺寸为660×714，我不太理解mask_3d_shift_s为什么要通过平方操作获得，以及mask_3d_shift_s的意义是什么？
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/99b35083-223d-46dd-ae90-16246ae461ca)

**Comment by Johnweii25** [comment]
> > 用 ubuntu 跑
> 
> 谢谢您的回复，我试试看。 还有一个小问题，在阅读代码的时候，看到了mask_3d_shift_s，mask是初始二维掩码660×660，mask_3d是mask经过28次复制后得到的660×660×28，而mask_3d_shift是经过平移后得到的660×714×28，那么mask_3d_shift_s是将mask_3d_shift每一个像素平方后，在图片维度相加，得到的尺寸为660×714，我不太理解mask_3d_shift_s为什么要通过平方操作获得，以及mask_3d_shift_s的意义是什么？ ![image](https://private-user-images.githubusercontent.com/128362316/283327658-99b35083-223d-46dd-ae90-16246ae461ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTU2NTIsIm5iZiI6MTcwNTM5NTM1MiwicGF0aCI6Ii8xMjgzNjIzMTYvMjgzMzI3NjU4LTk5YjM1MDgzLTIyM2QtNDZkZC1hZTkwLTE2MjQ2YWU0NjFjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwODU1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTVmNTVkY2U4NmRlMzQzNGQwZGE5YTg2NTUxYmMzY2Y1NzE4OGE4NTZlMTNkOWU1ZGEyMWEyMDk2NDA0YjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B7hOYDmcw6uCttp1aC-35ToE97hsnO2zthqt3QFnEKI)

请问用ubuntu 跑后结果如何，我目前也遇到这个问题。谢谢
