### ISSUE TITLE
mask 3d shift s

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#46]
在阅读代码的时候，看到了mask_3d_shift_s，我清楚mask是初始二维掩码660×660，mask_3d是mask经过28次复制后得到的660×660×28，而mask_3d_shift是经过平移后得到的660×714×28，那么mask_3d_shift_s是将mask_3d_shift每一个像素平方后，在图片维度相加，得到的尺寸为660×714，我不太理解mask_3d_shift_s为什么要通过平方操作获得，以及mask_3d_shift_s的意义是什么？希望能得到您的解答！非常感谢。
![27909e90906266c95f7c96dac7f3089](https://github.com/caiyuanhao1998/MST/assets/128362316/12762f1b-053d-4593-bed1-3d3224a54b23)

**Comment by caiyuanhao1998** [comment]
这个是TSA-Net搜集数据时保留的操作，我们follow了他们
