### ISSUE TITLE
关于真实实验

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#47]
学长您好，您在真实重建实验中，论文中并没有给出比较结果，只有目视比较，是因为没有ground truth吗？
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/a4569989-dbeb-487f-9dc2-3fd3070cd809)
此外，在真实实验中，您将图片裁剪为384*384的大小进行训练，训练出来的模型用660*714的的measurement进行测试，这样是否表明训练的模型所用的图片尺寸和测试所用的图片尺寸无关？

**Comment by caiyuanhao1998** [comment]
对的；还是有关系的

**Comment by dongruoyu1** [comment]
1、在您给出的链接下载的TSA_real_data中，有用来测试的五张measurements，并且包含了reconstruction的文件夹，里面是这五张压缩图像的重构图像，这个不是ground truth吗?还是说这个只是TSA-net作者用他们的方法给出的重构结果?
2、如果有关系的话，为什么不直接用660*714的高光谱图像进行训练模型呢，这样测试的结果不是更准确了吗?
很抱歉在深夜打扰您，您早点休息^^



---- 回复的原邮件 ----
| 发件人 | Yuanhao ***@***.***> |
| 日期 | 2023年11月22日 22:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [caiyuanhao1998/MST] 关于真实实验 (Issue #47) |

对的；还是有关系的

**Comment by caiyuanhao1998** [comment]
real train 代码已更新，欢迎使用
