### ISSUE TITLE
请问如果想要直接使用该功能，直接按照验证步骤，并在此之前把我的RGB转化成mat数据即可吗

### ISSUE THREAD

**Issue by 233AvavAvA** [caiyuanhao1998/MST#48]
非常感谢作者的贡献

**Comment by caiyuanhao1998** [comment]
你好，RGB转成高光谱图像并不是这个repo，而是另一个repo：[MST++](https://github.com/caiyuanhao1998/MST-plus-plus)

可以按照你说的这个操作顺序来使用[MST++](https://github.com/caiyuanhao1998/MST-plus-plus)，不需要转成.mat文件

如果感觉有用的话，帮忙点点star支持一下

**Comment by 233AvavAvA** [comment]
已star，谢谢大佬的回复



---原始邮件---
发件人: "Yuanhao ***@***.***&gt;
发送时间: 2023年11月24日(周五) 晚上9:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [caiyuanhao1998/MST] 请问如果想要直接使用该功能，直接按照验证步骤，并在此之前把我的RGB转化成mat数据即可吗 (Issue #48)




 
你好，RGB转成高光谱图像并不是这个repo，而是另一个repo：MST++
 
可以按照你说的这个操作顺序来使用MST++，不需要转成.mat文件
 
如果感觉有用的话，帮忙点点star支持一下
