### ISSUE TITLE
请问real训练过程为何掩码也进行随机裁剪

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#49]
real训练的时候对高光谱数据集裁剪为384*384*28的数据，而掩码也随机裁剪为384*384，这样岂不是每次裁剪出来的掩码是不一样的，而我们用来测试的时候，mask是660*660的，为什么不用660*660的mask加入训练？

**Comment by caiyuanhao1998** [comment]
因为660×660输入时，计算量太大，如果你有A100，当然也可以用660×660

**Comment by dongruoyu1** [comment]
如果按照384*384的随机掩码模型进行训练，而测试时我们用的measurement实际上是经过660*660的掩码并色散形成的，这样的训练模型是不是就说明measurement可以由任何其他的不一样但尺寸相同的掩码进行测试？
