### ISSUE TITLE
关于参数的疑问

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#50]
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/93040ee1-ce76-418c-b7dd-aa00797b632f)
您好，在您的脚本里有这样两个参数：input_setting和mask，他们的取值H, HM or Y和Phi, Phi_PhiPhiT, Mask or None，我对这两个参数代表的意义不是很理解，您能解释一下吗？非常感谢！

**Comment by caiyuanhao1998** [comment]
我论文里面有讲

**Comment by dongruoyu1** [comment]
您能大致提示一下范围吗，因为之前读了很多遍遍，确实没有找到，可能是我读到了但不知道是这个内容。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Yuanhao ***@***.***> |
| 日期 | 2023年11月29日 12:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [caiyuanhao1998/MST] 关于参数的疑问 (Issue #50) |

我论文里面有讲

**Comment by caiyuanhao1998** [comment]
就关于如何使用mask，input setting
