### ISSUE TITLE
数据集中RGB图像

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST#51]
作者您好，您是否有每一张高光谱图像所对应的RGB图像？repo里面只有simu test的10张和real test的5张所对应的RGB图像，您是否有训练集里每一张高光谱图像对应的RGB图像？非常感谢您的解答！

**Comment by caiyuanhao1998** [comment]
并没有，需要拿我们的可视化代码转一下，在 visualization 里面

**Comment by dongruoyu1** [comment]
作者您好，我在visu中没有找到可以将训练集高光谱图像合成为RGB图像的脚本，您说的是这里面中的哪一个？
![image](https://github.com/caiyuanhao1998/MST/assets/128362316/5bc0d0e8-c1d8-42cb-99d4-eb47bdb9766d)
