### ISSUE TITLE
Question about the ADMM-Net

### ISSUE THREAD

**Issue by 050644zf** [caiyuanhao1998/MST#52]
I found some differences in the [original ADMM-net](https://github.com/Phoenix-V/tensor-admm-net-sci/blob/master/Model/Decoder_Model.py) and [your implementation](https://github.com/caiyuanhao1998/MST/blob/main/simulation/train_code/architecture/ADMM_Net.py)

1. Original one has sparse inverse operation to achieve 2nd equation of formula (12) in [original paper](https://openaccess.thecvf.com/content_ICCV_2019/papers/Ma_Deep_Tensor_ADMM-Net_for_Snapshot_Compressive_Imaging_ICCV_2019_paper.pdf), while yours doesn't. Is there any change applied on formulas? 
2. Your implementation has multiple stages of U-Net which doesn't appear in original paper. Instead, I found [this paper](https://arxiv.org/abs/2301.06321) has similar usage of U-Net as denoising network here. Did you use U-Net as some kind of equivalent to part of the original ADMM-net or sth else?

**Comment by caiyuanhao1998** [comment]
1. We just change the unfolding scheme while keeping others the same.

2. We use multiple stages of Unets for fair comparison

**Comment by caiyuanhao1998** [comment]
If you find this repo helpful, please help us star it. Thanks
