### ISSUE TITLE
Real-architecture

### ISSUE THREAD

**Issue by Johnweii25** [caiyuanhao1998/MST#54]
recently im about to test cst,i found this error.these three parameters are unresolved,but it make sense in simulation.
<img width="438" alt="image" src="https://github.com/caiyuanhao1998/MST/assets/147235455/78fafee2-42f4-4896-b209-59e8310b5632">

**Comment by Johnweii25** [comment]
hello,i got another question,when i use test.py for one method,it dosen't generate one method Reconstructed HSI but five "660x660x28".mat,i open them with Matlab,but can't open with 'show_real.m'
![Screenshot from 2024-01-25 05-57-52](https://github.com/caiyuanhao1998/MST/assets/147235455/6a305f09-4e5b-4444-b785-d997f0658601)

**Comment by caiyuanhao1998** [comment]
CST does not use the physical mask in real scenes. Just input the measurement.
