### ISSUE TITLE
测试数据集转为RGB图像

### ISSUE THREAD

**Issue by YuhangQIN1024** [caiyuanhao1998/MST#56]
<img width="83" alt="屏幕截图 2024-03-14 183947" src="https://github.com/caiyuanhao1998/MST/assets/94520496/9ab3404f-d3d8-4c1c-a248-2da88f6adc66">
作者您好，DAUHST论文中图4左上角的RGB Image是如何生成的？visualization中的show simualtion只能生成每个通道的rgb图

**Comment by caiyuanhao1998** [comment]
你好，这里的RGB图像并不是转换得到的，而是直接下载的

We release the RGB images of [five real scenes](https://drive.google.com/drive/folders/1VTMgEbfX9MVpGo98XVVFKaANtQfgApAg?usp=sharing) and [ten simulation scenes](https://drive.google.com/drive/folders/1EkJsOxYKgyehZdOgKUeY75dU19GHZgE-?usp=sharing). Please feel free to check and use them.

如果想要从 RGB 转换到 HSI 的话，可以参考我们的另一个 repo [MST++](https://github.com/caiyuanhao1998/MST-plus-plus)
