### ISSUE TITLE
TwIST、GAP-TV、DeSCI的可视化结果

### ISSUE THREAD

**Issue by YuhangQIN1024** [caiyuanhao1998/MST#57]
作者您好，在您的论文实验结果部分中，您使用了TwIST、GAP-TV、DeSCI的PSNR、SSIM和可视化结果，但GitHub仓库中并没有这三个算法的可视化结果，请问您是否能提供这三个算法的可视化结果？

**Comment by caiyuanhao1998** [comment]
Hi, we have shared the reconstructed results of the three traditional methods. Please refer to the readme for the google drive and Baidu disk download links. Thanks.
