### ISSUE TITLE
这里乘2是什么意思

### ISSUE THREAD

**Issue by Matsuri247** [caiyuanhao1998/MST#58]
![Snipaste_2024-04-15_10-37-35](https://github.com/caiyuanhao1998/MST/assets/56073360/bb880798-0f03-46db-b915-a2f14d078f6b)
utils.py这部分代码我知道是在从gt里模拟出CASSI的单通道测量图作为网络的输入，meas = torch.sum(temp, 1)是在做成像过程里的“混叠”操作，但是meas = meas / nC * 2该如何解释呢？我有点想不明白，来请教您一下

**Comment by caiyuanhao1998** [comment]
这就是一个防止 用于初始化的measurement 过小的一个 trick，不必多想
