### ISSUE TITLE
优秀

### ISSUE THREAD

**Issue by xintangjin** [caiyuanhao1998/MST#6]
工作很优秀，这两年成果很丰富。但是指标已经刷到这么高了，但数据集还用的3、4年前的一套，有没有考虑过更新数据集？

**Comment by caiyuanhao1998** [comment]
网友你好，感谢你的关注

其实我们的MST在今年的高光谱数据上也有很好的效果，只不过不是SCI，而是RGB2HSI。
我们以MST为baseline，赢下了NTIRE 2022 Spectral Reconstruction Challenge的冠军。

请参照这个repo：https://github.com/caiyuanhao1998/MST-plus-plus

**Comment by duanNT** [comment]
我操你妈，你为什么盗我号点星星？

**Comment by luluchou** [comment]
作者是个傻逼！专门盗我号给他自己刷星星！干！
