### ISSUE TITLE
DAUHST的flops计算

### ISSUE THREAD

**Issue by aalekvar** [caiyuanhao1998/MST#60]
作者您好，我正在复现DAUSHT这篇工作，在开源代码里给的计算flops的函数在计算DAUHST时总是出现错误，我自己算的和论文中不太一致，想问一下DAUHST这篇的flops是如何计算的，谢谢！

**Comment by caiyuanhao1998** [comment]
你好，请使用 `simulation/test_code/utils.py` 中的 `my_summary()` 函数来计算 FLOPS。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下
