### ISSUE TITLE
关于test_s

### ISSUE THREAD

**Issue by zouge357** [caiyuanhao1998/MST#61]
请问test_s脚本的作用是什么？readme中好像并没有提到

**Comment by caiyuanhao1998** [comment]
你好，test_s.py 是与 train_s.py 搭配在 real scene 下进行小 patch 训练与测试的。后来我们把 test_s.py 与 test.py 合并后就没再在readme里面提及了，你也可以使用它试试。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢
