### ISSUE TITLE
关于归一化问题

### ISSUE THREAD

**Issue by zouge357** [caiyuanhao1998/MST#62]
您好，我在阅读源码时，发现您对压缩图像的归一化处理是除以28乘2乘1.2，除以28我理解，因为是28通道，您能解释一下后面乘2乘1.2的含义吗？
![image](https://github.com/caiyuanhao1998/MST/assets/96838185/5ca60bc8-2a0e-4f10-b5da-e8ddcbd2dd89)

**Comment by caiyuanhao1998** [comment]
此处乘2乘1.2是为了防止input signal的值过小，所以乘以一个scale factor，没有特定的物理含义

如果觉得我们的repo有用的话，帮忙点点star支持一下，感谢
