### ISSUE TITLE
一轮训练时间

### ISSUE THREAD

**Issue by chenxu2002** [caiyuanhao1998/MST#64]
用的colab L4GPU，一轮训练大概需要25分钟，请问正常吗？
<img width="580" alt="image" src="https://github.com/caiyuanhao1998/MST/assets/76509220/fd4868c2-5e39-498c-b4dd-7db2cafc38da">

**Comment by caiyuanhao1998** [comment]
你好，你训练的是哪个 model 呢？

**Comment by chenxu2002** [comment]
> 你好，你训练的是哪个 model 呢？



> 你好，你训练的是哪个 model 呢？

您好，我训练的是GAP_Net

**Comment by caiyuanhao1998** [comment]
几个stage呢？spatial size 多大？

**Comment by chenxu2002** [comment]
用的是您提供的源代码里的模型，9个stage

**Comment by caiyuanhao1998** [comment]
9stage 算正常的，别担心

如果觉得我们的repo有用的话，帮忙folk支持一下，感谢
