### ISSUE TITLE
mask_3d_shift和mask的关系

### ISSUE THREAD

**Issue by chenxu2002** [caiyuanhao1998/MST#65]
我希望在32维的高光谱数据上进行实验，但目前似乎都是28维的，请问如何生成32维的mask_3d_shift？加载数据已知mask是256*256的；mask_3d_shift是256*310*28的，我的理解是mask_3d_shift是在mask基础上生成的对角矩阵，每次平移2个单位，做了下数据比对发现似乎不是这样的，求教！

**Comment by caiyuanhao1998** [comment]
mask3dshift是基于 mask copy，平移得到的。和对角矩阵没关系。论文中介绍cassi系统部分有详细的公式，请参考那一部分

如果觉得我们的repo有用的话，帮忙点点star支持一下，感谢
