### ISSUE TITLE
关于DAUHST在真实实验中训练和测试问题

### ISSUE THREAD

**Issue by tkttd** [caiyuanhao1998/MST#66]
你好，我发现在真实实验的文件夹中，你们在构建DAUHST时，移除了原文中提出的线性投影步骤，和模型开端的噪声估计网络。

这似乎是和原文的方法论有冲突的，请问在真实实验中使用这样的设置是有什么原因吗？

**Comment by caiyuanhao1998** [comment]
你好，感谢关注。在 real 实验中，我们根据实际情况进行了调整。现在这套代码的视觉效果更好，你也可以使用 small patch 的训练方式（参考我们的 readme ），那种训练的视觉效果更好。

如果觉得我们的 repo 有用的话，帮我们点点 star 支持一下。感谢 :)
