### ISSUE TITLE
您好，关于可视化部分

### ISSUE THREAD

**Issue by zouge357** [caiyuanhao1998/MST#67]
![image](https://github.com/user-attachments/assets/28dbf4bf-d9ac-4c85-87f5-d9497b8bbd75)
您在该部分对黄色方框的内的图片一个个放大然后放在左下角，请问您是一个个处理的吗？有什么快捷的方法吗？

**Comment by caiyuanhao1998** [comment]
对的，人眼挑出来然后排在左下角的，当时挑的我眼睛都花了 :(
