### ISSUE TITLE
参数计算

### ISSUE THREAD

**Issue by zouge357** [caiyuanhao1998/MST#68]
你好，我在用您提供的my summary函数计算参数量的时候发生了这样的错误，请问您在计算的时候出现过这样的问题吗？非常感谢您的解答
![image](https://github.com/user-attachments/assets/71a831c7-d7bd-44eb-b7c1-ecc64faaed77)

**Comment by caiyuanhao1998** [comment]
你好，这个问题是 model 或者 input 没放到 cuda 上边，你试试 .cuda() 能不能传到 GPU 上

**Comment by zouge357** [comment]
我已经全部传到cuda上了，可能是fvcore版本的问题，您是什么版本的？

**Comment by zouge357** [comment]
![image](https://github.com/user-attachments/assets/bb4439d9-666c-41ab-a454-d4701a73abef)
你好，这是我修改后bug的结果，一些操作符没有被统计上，不知道这些是否会影响最终结果？

**Comment by caiyuanhao1998** [comment]
看上去是对的，真棒！
