### ISSUE TITLE
消融实验

### ISSUE THREAD

**Issue by zouge357** [caiyuanhao1998/MST#69]
您好，你在mst中第一个消融实验，分别去掉的是s-msa和mm，我想知道在实验的时候这个s-msa是指整个MSAB模块都去掉了，还是只去掉了ms-msa注意力，留下了两个正则化层和一个ffn
![image](https://github.com/user-attachments/assets/d693a637-3478-40fb-8e72-aa762fa6a582)
![image](https://github.com/user-attachments/assets/ddceafc3-587d-43c9-87be-531e097bd042)

**Comment by caiyuanhao1998** [comment]
你好，是指只去掉了ms-msa注意力，留下了两个正则化层和一个ffn
