### ISSUE TITLE
关于真实实验

### ISSUE THREAD

**Issue by zouge357** [caiyuanhao1998/MST#70]
我按照您的策略，将数据裁剪为384然后训练真实数据，然而训练出的mst_l的重构结果很差，没有您在readme中提供的图像中那么好。请问您知道这是怎么回事吗？前两张是我的重构结果，后两张是readme中链接提供的。
![image](https://github.com/user-attachments/assets/6035feeb-e18f-4772-a6bc-d2e4195c187c)
![image](https://github.com/user-attachments/assets/a5edfb5a-237c-4491-b01e-c0749194d063)
![image](https://github.com/user-attachments/assets/91cc9b00-c720-47af-80af-06ef47d94ca9)
![image](https://github.com/user-attachments/assets/9f27264a-2c43-4bee-af37-97fe66824265)

**Comment by caiyuanhao1998** [comment]
你好，感谢关注。

real 训练是需要实时监测的。并不一定是指标越高的视觉效果越好。另外建议你采用 `train_s.py` 脚本来训练模型，这个代码使用的是滑动切割 small patch 来训练，在 real 数据集上的视觉效果会好一些。希望能帮到你

**Comment by zouge357** [comment]
好的谢谢您，另外如果显存够用的话，是否直接用660×660的掩码和数据集相乘去训练数据重构效果会更好一些？

**Comment by zouge357** [comment]
> 你好，感谢关注。
> 
> real 训练是需要实时监测的。并不一定是指标越高的视觉效果越好。另外建议你采用 `train_s.py` 脚本来训练模型，这个代码使用的是滑动切割 small patch 来训练，在 real 数据集上的视觉效果会好一些。希望能帮到你

好的谢谢您，另外如果显存够用的话，是否直接用660×660的掩码和数据集相乘去训练数据重构效果会更好一些？

**Comment by caiyuanhao1998** [comment]
不会，小 patch 好一些
