### ISSUE TITLE
train_s

### ISSUE THREAD

**Issue by zouge357** [caiyuanhao1998/MST#71]
您好，关于您上午所说的train_s脚本我已经仔细阅读了一下，发现和train的区别就是训练尺寸大小从384改为96，同时训练的batch_size从1改为8，但是我并没有找到您说的“滑动切割”中的切割。具体在哪里吗？

**Comment by caiyuanhao1998** [comment]
噢噢，不好意思，我记错了，没有滑动切割，就是把 batch size 开大
