### ISSUE TITLE
Evaluation 

### ISSUE THREAD

**Issue by Johnweii25** [caiyuanhao1998/MST#73]
Hi, great work!
https://github.com/caiyuanhao1998/MST/blob/bd8f932a64a77838e7c1b58b0243caabfe055321/simulation/train_code/train.py#L108
in line 108 return ...psnr_list,ssim_list,how to evaluate a single  scene to evaluate its psnr and ssim compared with other methods?

**Comment by caiyuanhao1998** [comment]
Hi, the single scene is the length = 1 situation of the list :)

**Comment by Johnweii25** [comment]
did u mean this line change the 'test_gt.shape[0]'?
    for k in range(test_gt.shape[0]):

**Comment by Johnweii25** [comment]
Thanks
