### ISSUE TITLE
Simulation results visualization

### ISSUE THREAD

**Issue by Johnweii25** [caiyuanhao1998/MST#74]
Hi,how to get the ground truth visualized among the simulation results like the "Mask-guided Spectral-wise Transformer for Efficient Hyperspectral Image Reconstruction"
![image](https://github.com/user-attachments/assets/1ee0d5be-99f6-453c-a944-746fd3c47c3b)

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

Please use PPT to crop and zoom in

**Comment by Johnweii25** [comment]
> Hi, thanks for your interest,
> 
> Please use PPT to crop and zoom in
I don't think i made myself clear,i'm really curious how to got the ground truth?the coloured ground truth

**Comment by caiyuanhao1998** [comment]
OK, please use our visualization code to process the GT `.mat` file

**Comment by caiyuanhao1998** [comment]
follow our `README.MD` file for the instruction
