### ISSUE TITLE
数据增强中的问题

### ISSUE THREAD

**Issue by bozai27** [caiyuanhao1998/MST#75]
Hi，你的工作很好，我有一点疑问是否能够解答，
数据增强中采用分patch拼接的增强方法不会造成图片空间上的不连续吗？
simulation时采用的1024x1024x28的图片也是4张256x256的图片拼接的结果，这样不会使空间信息不连续吗？
我比较好奇有没有对上述两个问题做过消融。

**Comment by caiyuanhao1998** [comment]
你好，感谢关注
分patch是为了增多训练数据，在测试的时候是直接将一整个图像送进网络当中，并不是分 patch 来测
