### ISSUE TITLE
Outputs heat map

### ISSUE THREAD

**Issue by Johnweii25** [caiyuanhao1998/MST#77]
In Figure.7, it shows how the MM direct the model to focus on the effective area.I woder how you made it, is there any convience to share the code, thanks~

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

Just follow our paper to extract the feature map of MM and visualize it with the pseudo color.

**Comment by Johnweii25** [comment]
Thank you~ and is the feature a single channel? or the 28?

**Comment by caiyuanhao1998** [comment]
Average them

**Comment by Johnweii25** [comment]
Thanks~
