### ISSUE TITLE
ARAD_1K reproduction code

### ISSUE THREAD

**Issue by MortenHannemose** [caiyuanhao1998/MST#78]
Thank you for you repository!
Could you please provide code on how to run your model on https://github.com/boazarad/ARAD_1K?
I could not find it under datasets, and I'm unsure of which format it should have.

**Comment by caiyuanhao1998** [comment]
Hi, our README file already has the introduction on how to run on the ARAD_1K dataset. Please refer to it.

If you find our repo useful, please help us star it. Thanks.

**Comment by caiyuanhao1998** [comment]
Please refer to our another repo:

https://github.com/caiyuanhao1998/MST-plus-plus
