### ISSUE TITLE
Spectral interpolation

### ISSUE THREAD

**Issue by hx123456789199** [caiyuanhao1998/MST#80]
Hello, first of all thank you for your excellent work! I see that you mentioned in this article that the CAVE dataset is interpolated into 28 channels by interpolation, may I ask which interpolation method you used? I am looking forward to your reply. Thank you very much!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interests,

We follow the same interpolated datasets as TSA-Net. They use a special spectral response function for interpolation.

If you find our repo useful, please help us star it, thanks :)
