### ISSUE TITLE
the settings of the training datasets

### ISSUE THREAD

**Issue by XuWeizhu** [caiyuanhao1998/MST#81]
What is the difference between ‘CAVE dataset(cave_1024_28), CAVE(CAVE_512_28)，KAIST(KAIST_CVPR2021)’  and ‘Columbia2010, KSIAT SIGGRAPH2017'?  Some duplicate scenarios are also found in the dataset (cave_1024_28).

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

I guess the main difference between cave_1024_28 and CAVE_512_28 is the spatial resolution. 1024 vs 512.

As for other datasets, they contain different scenes, captured by different spectral cameras, derived by different spectral interpolation, etc.

**Comment by XuWeizhu** [comment]
I found some KAIST patches in cave_1024_28. It may be a mixed dataset.
