### ISSUE TITLE
关于CST的真实实验

### ISSUE THREAD

**Issue by GaussianRain** [caiyuanhao1998/MST#82]
CST代码在处理真实数据的时候似乎有问题。我看您是按384x384训练的，然后是分成16x16的小块。但是660并不能被16整除。请问在训练真实实验的时候是如何进行修改的

**Comment by caiyuanhao1998** [comment]
你好，感谢关注。

训练有两种模式，第一种是直接大的 patch size 训练 如 384x384，在 `train.py` 里面

还有一种，是在小的 patch size 上训练，如 96x96，在 `train_s.py` 里面

如果你觉得我们的 repo 有用的话，帮我们点点 star 支持一下吧 :)

**Comment by GaussianRain** [comment]
@caiyuanhao1998 您好，感谢您的答复，可能是我没有表述清楚。  具体而言是会有如下报错，因为660不是16的倍数，所以无法生成小的patch，w_size是否在真实实验中要进行更改，需要改成多少比较合适
  File "/home/cljcode/MST/real/test_code/architecture/CST.py", line 304, in forward
    x = rearrange(x, 'b (nh hh) (nw ww) c-> b (nh nw) (hh ww c)', hh=w_size[0] * 2, ww=w_size[1] * 2)
  File "/root/anaconda3/envs/dynaspec/lib/python3.10/site-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
  File "/root/anaconda3/envs/dynaspec/lib/python3.10/site-packages/einops/einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b (nh hh) (nw ww) c-> b (nh nw) (hh ww c)".
 Input tensor shape: torch.Size([1, 660, 660, 28]). Additional info: {'hh': 16, 'ww': 16}.
 Shape mismatch, can't divide axis of length 660 in chunks of 16

**Comment by Xinyi-Liang** [comment]
@GaussianRain 您好，请问您解决了吗。我也遇到了同样的问题
